"use client";

/**
 * AutoCreatedBadge — small visual indicator on invoice rows that
 * were auto-generated by the AI orphan classifier (Sesija 5)
 * rather than created by the user uploading a real invoice.
 *
 * Sesija 7 of the rēķini-redesign — added because Sesija 5's
 * placeholder invoices looked identical to user-created ones,
 * making it confusing what to do with them ("Why does this
 * invoice have number '(automātiski izveidots)' and no PDF?").
 *
 * Detection heuristic:
 *   - invoice number === '(automātiski izveidots)' OR
 *   - invoice number is empty AND description starts with
 *     'Automātiski izveidots no bankas:'
 *
 * On hover, shows a tooltip explaining what it is and what to do:
 *   "AI atpazina šo maksājumu pēc bankas izraksta un izveidoja
 *    rēķina vietturi. Atver, lai pievienotu īsto rēķinu (PDF) un
 *    rediģētu numuru, ja vajag."
 */

import { Sparkles } from "lucide-react";

interface AutoCreatedBadgeProps {
  /** The invoice number — may be the literal '(automātiski izveidots)' string */
  invoiceNumber?: string;
  /** Optional description — sometimes carries the marker instead */
  description?: string;
  /** Visual variant: 'inline' for small chip, 'tooltip-only' for icon
   *  in tight rows where text doesn't fit. Default 'inline'. */
  variant?: "inline" | "icon";
}

const AUTO_NUMBER_MARKER = "(automātiski izveidots)";
const AUTO_DESC_PREFIX = "Automātiski izveidots no bankas:";

export function isAutoCreated(input: AutoCreatedBadgeProps): boolean {
  if (input.invoiceNumber === AUTO_NUMBER_MARKER) return true;
  if (
    !input.invoiceNumber &&
    input.description?.startsWith(AUTO_DESC_PREFIX)
  ) {
    return true;
  }
  return false;
}

export function AutoCreatedBadge({
  invoiceNumber,
  description,
  variant = "inline",
}: AutoCreatedBadgeProps) {
  if (!isAutoCreated({ invoiceNumber, description })) return null;

  const tooltip =
    "AI atpazina šo maksājumu pēc bankas izraksta un izveidoja rēķina vietturi. Atver, lai pievienotu īsto rēķinu (PDF) un rediģētu numuru, ja vajag.";

  if (variant === "icon") {
    return (
      <span
        className="inline-flex items-center justify-center h-4 w-4 rounded bg-violet-100 text-violet-700"
        title={tooltip}
      >
        <Sparkles className="h-2.5 w-2.5" />
      </span>
    );
  }

  return (
    <span
      className="inline-flex items-center gap-1 rounded-md bg-violet-50 border border-violet-200 text-violet-800 px-1.5 py-0.5 text-[10.5px] font-medium"
      title={tooltip}
    >
      <Sparkles className="h-2.5 w-2.5" />
      AI izveidots
    </span>
  );
}
